### ISSUE TITLE
Missing files + font render issue on Android resize

### ISSUE THREAD

**Issue by danielmcconville** [matthewrdev/font-icons-in-xamarin-forms#2]
Hi, thanks for the code!

It looks like you have missed a couple of files from your project (ViewModelLocator & the Converters).

Additionally I experienced issues with the rendering of the fontawesome fonts in Android when re-sizing. I forked the repo and did a fix for both of these issues. I will issue a pull request so you can take a look.

**Comment by matthewrdev** [comment]
The missing files appear to be a symptom of me using MFractors code-gen :/

Thanks for the pull request, I've just merged it in.
